### ISSUE TITLE
コメントの作成②：自習室情報を有無別で記載できるようにする

### ISSUE THREAD

**Issue by nanako45a** [nanako45a/find_library#101]
①Commentモデルでそれぞれのenumを定義
【app/models/comment.rb】
```
class Comment < ApplicationRecord
  # enum定義
  enum comments_seats_number: {
    comments_seats_none: 0,        # 0席
    comments_seats_small: 1,       # 1〜20席
    comments_seats_medium: 2,      # 21〜50席
    comments_seats_large: 3,       # 51〜100席
    comments_seats_extra_large: 4, # 101席〜以上
    comments_seats_unknown: 5      # わからない
  }

  enum comments_pc_available: {
    comments_pc_unavailable: 0,  # PC利用不可
    comments_pc_available: 1,    # PC利用可能
    comments_pc_unknown: 2       # わからない
  }

  enum comments_wifi_available: {
    comments_wifi_unavailable: 0, # WiFi利用不可
    comments_wifi_available: 1,   # WiFi利用可能
    comments_wifi_unknown: 2      # わからない
  }

  enum comments_power_available: {
    comments_power_unavailable: 0, # 電源利用不可
    comments_power_available: 1,   # 電源利用可能
    comments_power_unknown: 2      # わからない
  }
end
```
②Commentモデルで定義したenumに対応する翻訳を言語ファイルに記述
【config/locales/ja.yml】
```
ja:
  # enumsセクション: 各モデルで定義したenumの日本語表示設定
  enums:
    # commentモデルで定義したenum
    comment:
      comments_seats_number:
        comments_seats_none: "0席"
        comments_seats_small: "1〜20席"
        comments_seats_medium: "21〜50席"
        comments_seats_large: "51〜100席"
        comments_seats_extra_large: "101席〜以上"
        comments_seats_unknown: "わからない"

      comments_pc_available:
        comments_pc_unavailable: "PC利用不可"
        comments_pc_available: "PC利用可能"
        comments_pc_unknown: "わからない"

      comments_wifi_available:
        comments_wifi_unavailable: "WiFi利用不可"
        comments_wifi_available: "WiFi利用可能"
        comments_wifi_unknown: "わからない"

      comments_power_available:
        comments_power_unavailable: "電源利用不可"
        comments_power_available: "電源利用可能"
        comments_power_unknown: "わからない"
```

③enumで定義したカラムがデータベースに存在するか確認
```
ActiveRecord::Schema[7.1].define(version: 2024_03_02_115838) do
  create_table "comments", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.text "comments_body"
  # enumで定義したカラム
    t.integer "comments_seats_number"
    t.integer "comments_pc_available"
    t.integer "comments_wifi_available"
    t.integer "comments_power_available"
   # ここまで
    t.bigint "library_id", null: false
    t.bigint "user_id", null: false
    t.index ["library_id"], name: "index_comments_on_library_id"
    t.index ["user_id"], name: "index_comments_on_user_id"
  end

  add_foreign_key "comments", "libraries"
  add_foreign_key "comments", "users"

end
```
④アプリ上で実際にコメントを投稿し、正常に保存できているか確認
```
irb(main):005> Comment.all
  Comment Load (8.0ms)  SELECT "comments".* FROM "comments" /* loading for pp */ LIMIT $1  [["LIMIT", 11]]
=> 
[#<Comment:0x000000010ab8ca80
  id: 8,
  created_at:
   Mon, 04 Mar 2024 13:53:58.744005000 JST +09:00,
  updated_at:
   Mon, 04 Mar 2024 13:53:58.744005000 JST +09:00,
  comments_body: "wifi接続良好でした",
  comments_seats_number: 4,
  comments_pc_available: 1,
  comments_wifi_available: 1,
  comments_power_available: 1,
  library_id: 25,
  user_id: 5>]
```
→問題なし
